<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IntranetTiendas.Web</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
    <UserSecretsId>ff9e592c-baaa-47fb-88f3-601e19381518</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

</Project>
